[project]
name = "ex1"
version = "1.0.0"
description = "Matrix data analysis"
authors = [{name = "carlinaq"}]
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0",
    "numpy>=1.24",
    "matplotlib>=3.7",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"